version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: The Second Step
          command: |
            ls -al
            echo '^^^The files in your repo^^^'


# version: 2.1

# orbs:
#   node: circleci/node@4.1

# jobs:
#   runner:
#     machine: true
#     resource_class: devinmarieb/sample-project
#     steps:
#       - run: echo "Hi I'm on runners finally!"
#   one:
#     docker:
#       - image: cimg/ruby:2.6.8
#         auth:
#           username: mydockerhub-user
#           password: $DOCKERHUB_PASSWORD

#     steps:
#       - checkout
#       - run: echo "A first hello"
#       - run: sleep 25
#   two:
#     docker:
#       - image: cimg/ruby:3.0.2
#         auth:
#           username: mydockerhub-user
#           password: $DOCKERHUB_PASSWORD
#     steps:
#       - checkout
#       - run: echo "A second hello"
#       - run: sleep 15
#   test:
#     # These next lines define a docker executor: https://circleci.com/docs/2.0/executor-types/
#     # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
#     # A list of available CircleCI docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/node
#     docker:
#       - image: cimg/node:15.1
#     steps:
#       # Checkout the code as the first step.
#       - checkout
#       - node/install-packages
#       - run:
#           name: Run tests
#           command: npm test

# workflows:
#   sample:
#     jobs:
#       - test
#       - runner
#       - one
#       - two
